// Generated by ai-qa-pipeline. Run run-5ba5404f, attempt 1.
// Source: TC-004 v5 "Signing out returns to the sign-in page". Provider: ollama, model: qwen2.5-coder:7b.
// Status: candidate awaiting human review. Do not edit in place; approve or reject the run.
import { test, users } from '../../../src/fixtures/test.js';

test.describe('Auth', () => {
  test('Signing out returns to the sign-in page', { tag: '@TC-004' }, async ({ app, signInAs }) => {
    await signInAs(users.employee);

    await app.dashboard.signOut();

    await app.login.expectSignInFormVisible();
  });
});
