// Generated by ai-qa-pipeline. Run run-a401834d, attempt 1.
// Source: TC-010 v2 "Employee can submit an annual leave request". Provider: ollama, model: qwen2.5-coder:7b.
// Status: candidate awaiting human review. Do not edit in place; approve or reject the run.
import { addDays, mondayWeeksAhead, test, users } from '../../../src/fixtures/test.js';

test.describe('Leave requests', () => {
  test(
    'Employee can submit an annual leave request',
    { tag: '@TC-010' },
    async ({ app, signInAs }) => {
      await signInAs(users.employee);
      const monday = mondayWeeksAhead(4);

      await app.leave.goto();
      await app.leave.expectRemaining(20);
      await app.leave.openRequestForm();
      await app.leaveForm.submitRequest({
        type: 'annual',
        startDate: monday,
        endDate: addDays(monday, 2),
        reason: 'Long weekend away',
      });

      await app.leave.expectSuccess('Leave request submitted for approval (3 working days)');
      await app.leave.expectRequestListed('lr-101', 'Pending');
      await app.leave.expectRemaining(17);
    },
  );
});
