// Generated by ai-qa-pipeline. Run run-b534878a, attempt 1.
// Source: TC-030 v2 "Manager approves a direct report's leave request". Provider: ollama, model: qwen2.5-coder:7b.
// Status: candidate awaiting human review. Do not edit in place; approve or reject the run.
import { test, users } from '../../../src/fixtures/test.js';

test.describe('Manager approvals', () => {
  test(
    "Manager approves a direct report's leave request",
    { tag: '@TC-030' },
    async ({ app, signInAs }) => {
      await signInAs(users.engineeringManager);

      await app.approvals.goto();
      await app.approvals.expectLeaveAwaiting('lr-001');
      await app.approvals.approveLeave('lr-001');

      await app.approvals.expectSuccess('Leave request for Dev Patel approved.');
      await app.approvals.expectLeaveNotAwaiting('lr-001');
    },
  );
});
