// Generated by ai-qa-pipeline. Run run-c632f933, attempt 1.
// Source: TC-045 v2 "A reactivated employee can sign in again". Provider: ollama, model: qwen2.5-coder:7b.
// Status: candidate awaiting human review. Do not edit in place; approve or reject the run.
import { test, users } from '../../../src/fixtures/test.js';

test.describe('Employees', () => {
  test(
    'A reactivated employee can sign in again',
    { tag: '@TC-045' },
    async ({ app, signInAs }) => {
      await signInAs(users.admin);

      await app.employees.goto();
      await app.employees.reactivate(users.deactivated.id);

      await app.employees.expectSuccess('Leon Baptiste has been reactivated.');
      await app.employees.expectStatus(users.deactivated.id, 'Active');

      await app.employees.signOut();
      await app.login.goto();
      await app.login.signIn(users.deactivated.email, users.deactivated.password);

      await app.dashboard.expectLoadedFor('Leon');
    },
  );
});
